version: '3.5'

services:
  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432
  postgres-test:
    image: postgres:11.2
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5434:5432




