version: '3.5'

networks:
  internal:
    driver: bridge

services:
  prod-postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5444:5432
    networks:
      - internal
  app:
    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: npm run prod
    depends_on:
      - prod-postgres
    ports:
      - 3333:3000
    networks:
      - internal





